{
    "name": "AUTO-INFO : HR Expense Cash Tracking",
    "version": "15.0.1.1.0",
    "category": "AUTO-INFO : ERP Expenses",
    "summary": "Expense cash reimbursement with Expense Category UX simplification and XLSX exports",
    "author": "Odoo S.A., Dataroot Asia Co., Ltd., The Auto-Info Co., Ltd.",
    "website": "https://www.dataroot.asia/support-odoo",
    "license": "OPL-1",
    "depends": [
        "hr_expense",
        "mail",
        "analytic",
        "report_xlsx",
        "base_tier_validation",
        "dtr_expense_tier_validation",
    ],
    "data": [
        "security/expense_cash_security.xml",
        "security/expense_cash_rules.xml",
        "security/ir.model.access.csv",
        "data/expense_cash_mail_templates.xml",
        "wizard/expense_return_reason_wizard_views.xml",
        "wizard/expense_cash_summary_xlsx_wizard_views.xml",
        "data/expense_cash_xlsx_actions.xml",
        "views/expense_approval_role_views.xml",
        "views/expense_approval_delegate_views.xml",
        "views/expense_category_views.xml",
        "views/hr_expense_views.xml",
        "views/hr_expense_sheet_views.xml",
    ],
    "installable": True,
    "application": False,
}
